version: '3.8'

services:
  loveyourstory-db:
    image: postgres:17.5
    container_name: loveyourstory-db
    environment:
      POSTGRES_USER: loveyourstory_admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: loveyourstory-db
    restart: always
    networks: #
      - nestjs-network
    ports:
      - "5434:5432"
networks:
  nestjs-network:

#docker ps => #to check running containers

#run all containers in detached mode
#run: docker compose up -d

#run specific container
#run: docker compose up -d loveyourstory-db -d